cmake_minimum_required(VERSION 3.5)
project(spe)

# Create an option to switch between a system sdl library and a vendored SDL library
option(BUILD_SHARED_LIBS "Build using shared libraries" OFF)
option(SPE_VENDORED "Use vendored libraries" ON)

if(SPE_VENDORED)
    # This assumes you have added SDL as a submodule in vendored/SDL
    add_subdirectory(SDL)
else()
    # 1. Look for a SDL3 package,
    # 2. look for the SDL3-shared component, and
    # 3. fail if the shared component cannot be found.
    find_package(SDL3 REQUIRED CONFIG REQUIRED COMPONENTS SDL3-shared)
endif()

# Create your game executable target as usual
add_executable(spe WIN32 main.cpp)

# Link to the actual SDL3 library.
target_link_libraries(spe PRIVATE SDL3::SDL3)
